### ISSUE TITLE
HistoryViewerField hides version number

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-versioned-admin#188]
Version: 1.6.0

When loading the HistoryViewerField on a custom DataObject, the table is cut off on either side.

![image](https://user-images.githubusercontent.com/10215604/99209654-862f9400-2828-11eb-912c-ec06dd048cd9.png)

From a brief investigation, this rule is the cause of the issue

![image](https://user-images.githubusercontent.com/10215604/99209738-b840f600-2828-11eb-9dc4-8a72a2a5984c.png)

**Comment by robbieaverill** [comment]
From memory we have a prop, or a class or something that you can pass which says whether the history viewer is embedded in a ModelAdmin or a CMSMain interface, and the horizontal margins are adjusted by this. Looks like this example is a custom implementation in a ModelAdmin, so perhaps that horrible flakey styling logic has broken since it was originally written.

**Comment by michalkleiner** [comment]
PR merged
