### ISSUE TITLE
Javascript requirements in docs can cause issues 

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-versioned-admin#189]
The docs in [here](https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#using-the-history-viewer) specify to require the custom app bundle in getCMSFields

![image](https://user-images.githubusercontent.com/10215604/99210199-13271d00-282a-11eb-97b9-289e0548a2bd.png)

I've run into an issue when loading a DataObject via ajax (clicking an item in a gridfield to load the DataObject) it doesn't pull in the required javascript. The workaround we've used to get this working was is below to ensure the javascript is always loaded:

![image](https://user-images.githubusercontent.com/10215604/99210332-6305e400-282a-11eb-91e2-a876aa69cdc0.png)

Note: For consistent results we've found we needed all of those "After" statements

**Comment by robbieaverill** [comment]
Your suggested implementation is the correct way to pull JavaScript into SilverStripe 4 projects. Since dynamically loading JavaScript (as in the first example, and how it was done in SilverStripe 3 [doesn't always work](https://github.com/silverstripe/silverstripe-admin/issues/897) it's better to do what you've done in your second example and load it globally.

Would you like to update the documentation?
