### ISSUE TITLE
Page history tab doesn't work at all with GraphQL 4

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-versioned-admin#196]
Affects 1.x-dev

Clicking on the page history tab when using graphql 4 (dev-master) leads to an infinite loading symbol

browser console - xhr response from server /admin/graphql:

![image](https://user-images.githubusercontent.com/4809037/106402512-b2090000-648e-11eb-8ed6-dafd4cc9d269.png)

Expanding the first error:

![image](https://user-images.githubusercontent.com/4809037/106402542-d238bf00-648e-11eb-913f-daae24a34e5f.png)

It leads to this behat job failing in travis:
https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-versioned-admin/215295535/478451842/screenshots/list-view.feature_60.png
https://travis-ci.com/github/silverstripe/silverstripe-versioned-admin/jobs/478451842

**Comment by unclecheese** [comment]
Error is caused by inability to infer type from `DataObjectModel::getField('versions')` because it comes back as `ArrayList` with no `dataClass()`. Could set `dataClass()` explicitly in `Versioned`, but I don't think that's correct as the list doesn't contain the actual dataobjects, but rather a variant thereof.

The plugins here are probably going to be borked anyway, because the resolvers are going to get back ArrayList, which means they'll be doing post-query `limit()` and `offset()`. Yikes. 

Proper fix here, I think, is to make the versioning plugin smarter and assign the pagination plugin itself using its own homespun resolver for dealing with `DataObject::Versions()` (e.g. passing limit and offset as args instead of chained methods)

**Comment by chillu** [comment]
Started a PR on GraphQL v4 compat in https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/pull/60

**Comment by emteknetnz** [comment]
No longer an issue
