### ISSUE TITLE
Compare diff isn't working

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-versioned-admin#212]
CWP-2.8.0-rc1

I can "compare" versions, though there is not a content diff i.e. the green/red diff of text changes between versions

Instead it seemed like it only showed the most recent version

I see this on `/admin/pages/history/show/6132`

![image](https://user-images.githubusercontent.com/4809037/118909777-9b23e600-b977-11eb-8c18-88e75074bf80.png)

The content 'diff text' is on the latest version, but not the older version that I'm comparing against

Tested in IE11 and Firefox

## Acceptance Criteria
- [x] Text added without a matching deleted sample is highlighted in green
- [x] Deleted text style is retained

## Notes
- This never worked in Safari before ... we don't expect it to.
- There's a weird code snippet that's been copied in our codebase to handle the diff generation. If it's possible to patch it, great! Otherwise we might need to look for an alternative library.

## Pull Requests
- #237

**Comment by maxime-rainville** [comment]
I'm only getting a diff when content is deleted/replace.

When brand new content is added that doesn't get highlighted. 

# Initial version
![image](https://user-images.githubusercontent.com/1168676/119062613-5bb6d180-ba2b-11eb-88a6-1a4ad52f2ea6.png)

# Updated version
![image](https://user-images.githubusercontent.com/1168676/119062589-4772d480-ba2b-11eb-9242-79aff2041f72.png)

# Diff
![image](https://user-images.githubusercontent.com/1168676/119062564-35913180-ba2b-11eb-9194-e365dd18cb79.png)

**Comment by brynwhyman** [comment]
This was called out as a regression but I'm wondering if it indeed is... There are some related issues out there already:
* [Diff doesn't show an entirely new line as an addition](https://github.com/silverstripe/silverstripe-versioned-admin/issues/82)
* [No colour indicating changes between blocks on pages](https://github.com/silverstripe/silverstripe-versioned-admin/issues/111)

**Comment by emteknetnz** [comment]
Replicated in cms 4.7.x-dev - so it's not a regression, it's an existing issue

**Comment by GuySartorelli** [comment]
## What's happening
This is a styling issue.  It is caused by the `<ins>` tag surrounding the new `<p>` tag and its content. Deletions of entire paragraphs also don't get the appropriate `background-color` applied, though the deleted content does get strikethrough applied.
`ins` and `del` elements _are_ allowed to contain `p` (and other block-level) tags, but then their `display` style must be changed, as it's `inline` by default.

## Easy solution: Use `display: inline-block`
There's unfortunately no parent selector in css yet, so I can't add a style that says "style any `ins` or `del` elements that contain `p` or `div` tags with `display:block`. Setting all `ins` or `del` tags to `display:inline-block` will slightly change the appearance of the tags, but is definitely the easiest solution.

Current appearance:
![image](https://user-images.githubusercontent.com/36352093/162358619-0db93d5d-debd-436f-ae4e-010199ace073.png)

Using `inline-block`:
![image](https://user-images.githubusercontent.com/36352093/162358754-e75fb649-bf0d-4e9e-9f1a-57e357605b48.png)

## Harder solution: Push the `del` and `ins` tags inside the block-level elements.
We could check for any `del` and `ins` tags that contain block-level elements, and invert them so the block-level element instead contains the `del` or `ins` tag. This will retain the current styling, but may look a little strange for longer paragraphs - not sure which is more desirable. This approach also has more edge cases (e.g. making sure we catch all block-level elements, plus what happens with nested block-level elements?)
This can be done either with an HTML parser in the php code or using javascript on the client-side.

**Comment by emteknetnz** [comment]
The inline-block solution seems fine and unlikely to cause regressions?  Is there actually a downside to going with this?

**Comment by GuySartorelli** [comment]
I can't think of any downside provided there's no complaints about the slight style change.
I'm aware we used to have a designer in product to look at stuff like this so I figured in lieu of that I'd just give you and Max a chance to let me know if it's okay before I make the change.

**Comment by emteknetnz** [comment]
Go for it

**Comment by emteknetnz** [comment]
Linked PR has been merged
