### ISSUE TITLE
`CMSPageHistoryViewerController` should be default `CMSPageHistoryController` in SS 4.3

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-versioned-admin#67]
`CMSPageHistoryViewerController` has achieved feature parity with `CMSPageHistoryController`.

It should be the default controller for displaying Page History information when versioned-history is installed. An entry to the 4.3 change log should explain how to revert to the old controller.

Do we want to mark `CMSPageHistoryController` as deprecated in SS5 onwards?

# Pull requests
* [x] https://github.com/dnadesign/silverstripe-elemental/pull/463
* [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/71
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8508
* [x] https://github.com/silverstripe/silverstripe-cms/pull/2298
* [x] https://github.com/silverstripe/silverstripe-cms/pull/2300

**Comment by chillu** [comment]
@NightJar @robbieaverill Is there any reason this can't be done for 4.3? The goal of these shared core UI components should be to roll them out in all use cases, so we can't call it "done" just because Elemental uses it. Next time, if your team doesn't have the capacity to get it into that state (so planning for a partial roll out), please ensure that there's a follow up ticket which can be triaged and prioritised between teams. /cc @brynwhyman

**Comment by chillu** [comment]
> Do we want to mark CMSPageHistoryController as deprecated in SS5 onwards?

There's going to be so many UI controller changes in SS 5.x (ideally they all go away) that I think it's not a high priority. We should clearly spell out the relationship between the old and new controllers though (X replaces Y in both PHPDocs)

**Comment by robbieaverill** [comment]
> Is there any reason this can't be done for 4.3?

Nope. We refrained from shipping it by default with 4.2 because it didn't have compare mode. Now that it does it can be enabled for all pages.

We need to remove most of the logic from `HistoryControllerFactory::create()`, leaving the functionality for `isEnabled()` (with its extension) point to opt for the old controller still, because semver.

**Comment by maxime-rainville** [comment]
Fixing this issue will probably fix https://github.com/silverstripe/silverstripe-cms/issues/2277#issuecomment-428815482 as well.

**Comment by chillu** [comment]
Please mark any legacy functionality and means to switch to it (YAML config) as deprecated with a target of 5.x. What would be a use case for third party code to rely on the old functionality? I can't find any open source modules extending it at least: https://github.com/search?q=%22extends+CMSPageHistoryController%22&type=Code. Let's make it obvious that the old API won't be maintained beyond critical bugfixes (in code comments). We can't keep adding new functionality in addition to maintaining the old way. GridField will be a notable exception, because of it's large customisation and adoption surface.
